apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-arbpdqkj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-arbpdqkj 
  name: go-arbpdqkj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-arbpdqkj
    weight: 100 
